# Generated by Django 3.2.6 on 2021-09-25 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('display_name', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default_profile_pic.jpg', force_format=None, keep_meta=True, null=True, quality=85, size=[300, 300], upload_to='profile_pictures')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField(max_length=280)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('formatted_date_time', models.CharField(blank=True, max_length=50, null=True)),
                ('is_retweet', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('retweets', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_tweets', to=settings.AUTH_USER_MODEL)),
                ('retweeted_by', models.ManyToManyField(blank=True, related_name='retweeted_tweets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('tweet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lowbudgettwitterapp.tweet')),
                ('referenced_tweet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='lowbudgettwitterapp.tweet')),
            ],
            bases=('lowbudgettwitterapp.tweet',),
        ),
    ]
