# Generated by Django 3.2.6 on 2021-09-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lowbudgettwitterapp', '0002_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='lowbudgettwitterapp.account'),
            preserve_default=False,
        ),
    ]
