# Generated by Django 3.2.6 on 2021-09-26 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowbudgettwitterapp', '0003_following_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='account',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='following',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
